const SUPABASE_URL="https://xpzufexzbrlddthdgve.supabase.co",SUPABASE_ANON_KEY="sb_publishable_MVBg7lMChhL52f30zx-JxA_SBL1vSHZ";const sb=supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);const $=id=>document.getElementById(id);
async function auth(){const {data}=await sb.auth.getSession();if(data.session){$("loginPanel").classList.add("hidden");$("dashboard").classList.remove("hidden");$("logout").classList.remove("hidden");loadAdmin()}}
$("loginForm").addEventListener("submit",async e=>{e.preventDefault();$("loginMsg").textContent="Signing in…";const {error}=await sb.auth.signInWithPassword({email:$("email").value,password:$("password").value});if(error){$("loginMsg").textContent=error.message;return}await auth()});
$("logout").addEventListener("click",async()=>{await sb.auth.signOut();location.reload()});
async function api(url,opts={}){const {data}=await sb.auth.getSession(),token=data.session?.access_token;if(!token)throw Error("Not signed in");const r=await fetch(url,{...opts,headers:{Authorization:"Bearer "+token,"Content-Type":"application/json",...(opts.headers||{})}});const d=await r.json();if(!r.ok)throw Error(d.error||"Request failed");return d}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function loadAdmin(){try{const d=await api("/api/articles?admin=1");$("articleList").innerHTML=d.length?d.map(a=>'<button class="admin-row" data-id="'+a.id+'"><span><b>'+esc(a.title)+'</b><small>'+esc(a.category)+' · '+esc(a.status)+'</small></span><span>→</span></button>').join(""):'<div class="empty">No articles yet. Create the first one.</div>';document.querySelectorAll(".admin-row").forEach(x=>x.onclick=()=>edit(d.find(a=>String(a.id)===x.dataset.id)))}catch(e){$("adminMsg").textContent=e.message}}
function edit(a){$("editor").classList.remove("hidden");$("articleId").value=a.id;$("title").value=a.title;$("slug").value=a.slug;$("category").value=a.category;$("status").value=a.status;$("excerpt").value=a.excerpt||"";$("tags").value=(a.tags||[]).join(", ");$("content").value=a.content||"";scrollTo({top:document.body.scrollHeight,behavior:"smooth"})}
$("newArticle").onclick=()=>{$("editor").classList.remove("hidden");$("articleId").value="";$("title").value="";$("slug").value="";$("category").value="";$("status").value="draft";$("excerpt").value="";$("tags").value="";$("content").value=""};
$("cancelEdit").onclick=()=>$("editor").classList.add("hidden");
$("editor").addEventListener("submit",async e=>{e.preventDefault();$("editorMsg").textContent="Saving…";try{const id=$("articleId").value,body={title:$("title").value,slug:$("slug").value,category:$("category").value,status:$("status").value,excerpt:$("excerpt").value,tags:$("tags").value.split(",").map(x=>x.trim()).filter(Boolean),content:$("content").value};await api("/api/articles"+(id?"?id="+encodeURIComponent(id):""),{method:id?"PUT":"POST",body:JSON.stringify({...body,id})});$("editorMsg").textContent="Saved ✓";await loadAdmin()}catch(e){$("editorMsg").textContent=e.message}});
$("deleteArticle").onclick=async()=>{const id=$("articleId").value;if(!id||!confirm("Delete this article?"))return;try{await api("/api/articles?id="+encodeURIComponent(id),{method:"DELETE"});$("editor").classList.add("hidden");await loadAdmin()}catch(e){$("editorMsg").textContent=e.message}};
auth();