const SUPABASE_URL="https://xpzufexzbrlddthdvgve.supabase.co",SUPABASE_ANON_KEY="sb_publishable_MVBg7lMChhL52f30zx-JxA_SBL1vSHZ";const sb=supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);const $=id=>document.getElementById(id);
async function auth(){const {data}=await sb.auth.getSession();if(data.session){$("loginPanel").classList.add("hidden");$("dashboard").classList.remove("hidden");$("logout").classList.remove("hidden");await loadAdmin()}}
$("loginForm").addEventListener("submit",async e=>{e.preventDefault();$("loginMsg").textContent="Signing in…";const {error}=await sb.auth.signInWithPassword({email:$("email").value,password:$("password").value});if(error){$("loginMsg").textContent=error.message;return}await auth()});
$("logout").addEventListener("click",async()=>{await sb.auth.signOut();location.reload()});
function slugify(s){return String(s||"").trim().toLowerCase().replace(/[^a-z0-9-]+/g,"-").replace(/^-|-$/g,"")}
function cleanArticle(){const status=$("status").value==="published"?"published":"draft";return{title:$("title").value.trim(),slug:slugify($("slug").value),category:$("category").value.trim(),status,published:status==="published",published_at:status==="published"?new Date().toISOString():null,excerpt:$("excerpt").value.trim(),tags:$("tags").value.split(",").map(x=>x.trim()).filter(Boolean),content:$("content").value,cover_image:$("coverImage").value.trim()||null,seo_title:$("seoTitle").value.trim()||null,seo_description:$("seoDescription").value.trim()||null,canonical_url:$("canonicalUrl").value.trim()||null}}
async function loadAdmin(){try{const {data,error}=await sb.from("articles").select("*").order("updated_at",{ascending:false});if(error)throw error;$("adminMsg").textContent="";$("articleList").innerHTML=data.length?data.map(a=>'<button class="admin-row" data-id="'+a.id+'"><span><b>'+esc(a.title)+'</b><small>'+esc(a.category)+" · "+esc(a.status)+'</small></span><span>→</span></button>').join(""):'<div class="empty">No articles yet. Create the first one.</div>';document.querySelectorAll(".admin-row").forEach(x=>x.onclick=()=>edit(data.find(a=>String(a.id)===x.dataset.id)))}catch(e){$("adminMsg").textContent=e.message||"Could not load articles"}}
function edit(a){$("editor").classList.remove("hidden");$("articleId").value=a.id;$("title").value=a.title;$("slug").value=a.slug;$("slug").dataset.touched="1";$("category").value=a.category;$("status").value=a.status;$("excerpt").value=a.excerpt||"";$("tags").value=(a.tags||[]).join(", ");$("coverImage").value=a.cover_image||"";$("socialImage").value=a.cover_image||"";$("seoTitle").value=a.seo_title||"";$("seoDescription").value=a.seo_description||"";$("canonicalUrl").value=a.canonical_url||"";$("coverFile").value="";$("content").value=a.content||"";renderPreview();scrollTo({top:document.body.scrollHeight,behavior:"smooth"})}
$("newArticle").onclick=()=>{$("editor").classList.remove("hidden");$("articleId").value="";$("title").value="";$("slug").value="";$("slug").dataset.touched="";$("category").value="";$("status").value="draft";$("excerpt").value="";$("tags").value="";$("coverFile").value="";$("coverImage").value="";$("socialImage").value="";$("seoTitle").value="";$("seoDescription").value="";$("canonicalUrl").value="";$("content").value="";renderPreview();scrollTo({top:document.body.scrollHeight,behavior:"smooth"})};
$("cancelEdit").onclick=()=>$("editor").classList.add("hidden");
$("title").addEventListener("input",()=>{if(!$("slug").dataset.touched)$("slug").value=slugify($("title").value)});
$("slug").addEventListener("input",()=>{$("slug").dataset.touched=$("slug").value?"1":""});
$("content").addEventListener("input",renderPreview);
function renderPreview(){const raw=$("content").value.trim();$("preview").innerHTML=raw?DOMPurify.sanitize(marked.parse(raw)):'<p class="muted">Start writing to preview your article.</p>'}
function insertAtCursor(text){const ta=$("content"),start=ta.selectionStart,end=ta.selectionEnd,selected=ta.value.slice(start,end);let value=text;if(text==="**bold**"&&selected)value="**"+selected+"**";else if(text==="*italic*"&&selected)value="*"+selected+"*";else if(text==="[link text](https://example.com)"&&selected)value="["+selected+"](https://example.com)";ta.value=ta.value.slice(0,start)+value+ta.value.slice(end);ta.focus();const pos=start+value.length;ta.setSelectionRange(pos,pos);renderPreview()}
document.querySelectorAll("[data-md]").forEach(b=>b.addEventListener("click",()=>insertAtCursor(b.dataset.md)));
$("insertLink").onclick=()=>insertAtCursor("[link text](https://example.com)");
$("insertImage").onclick=()=>{const url=$("coverImage").value.trim();insertAtCursor(url?"![Cover image]("+url+")":"![alt text](https://example.com/image.jpg)")};
$("coverFile").addEventListener("change",async()=>{const file=$("coverFile").files[0];if(!file)return;if(file.size>5*1024*1024){$("editorMsg").textContent="Image is too large. Max 5 MB.";return}$("editorMsg").textContent="Uploading image…";try{const ext=(file.name.split(".").pop()||"jpg").toLowerCase();const path="covers/"+crypto.randomUUID()+"."+ext;const {error}=await sb.storage.from("article-images").upload(path,file,{cacheControl:"31536000",upsert:false,contentType:file.type});if(error)throw error;const {data}=sb.storage.from("article-images").getPublicUrl(path);$("coverImage").value=data.publicUrl;$("socialImage").value=data.publicUrl;$("editorMsg").textContent="Image uploaded ✓";renderPreview()}catch(e){$("editorMsg").textContent=e.message||"Image upload failed"}});
$("editor").addEventListener("submit",async e=>{e.preventDefault();$("editorMsg").textContent="Saving…";try{const id=$("articleId").value,body=cleanArticle();if(!body.title||!body.slug||!body.content||!body.category)throw Error("Title, slug, category and content are required");if(id){const {error}=await sb.from("articles").update(body).eq("id",id);if(error)throw error}else{const {error}=await sb.from("articles").insert(body);if(error)throw error}$("editorMsg").textContent="Saved ✓";await loadAdmin()}catch(e){$("editorMsg").textContent=e.message||"Save failed"}});
$("deleteArticle").onclick=async()=>{const id=$("articleId").value;if(!id||!confirm("Delete this article?"))return;try{const {error}=await sb.from("articles").delete().eq("id",id);if(error)throw error;$("editor").classList.add("hidden");$("editorMsg").textContent="";await loadAdmin()}catch(e){$("editorMsg").textContent=e.message||"Delete failed"}};
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}auth();
function autoSeo(){if(!$('seoTitle').value.trim())$('seoTitle').value=$('title').value.trim().slice(0,60);if(!$('seoDescription').value.trim())$('seoDescription').value=($('excerpt').value.trim()||$('content').value.replace(/[#*_>\[\]()]/g,' ').replace(/\s+/g,' ').trim()).slice(0,160);if(!$('canonicalUrl').value.trim()&&$('slug').value.trim())$('canonicalUrl').value=location.origin+'/article.html?slug='+encodeURIComponent(slugify($('slug').value))}
$('title').addEventListener('blur',autoSeo);$('excerpt').addEventListener('blur',autoSeo);$('slug').addEventListener('blur',autoSeo);
$('previewArticle').onclick=()=>{autoSeo();const title=esc($('title').value||'Untitled article'),excerpt=esc($('excerpt').value||''),cover=$('coverImage').value.trim();$('previewArticleBox').innerHTML='<p class="eyebrow">'+esc($('category').value||'CATEGORY')+'</p><h1 class="preview-title">'+title+'</h1>'+(cover?'<img class="article-cover" src="'+esc(cover)+'" alt="">':'')+'<p class="article-meta">Preview · '+esc($('status').value)+'</p>'+(excerpt?'<p class="preview-excerpt">'+excerpt+'</p>':'')+'<div class="markdown">'+DOMPurify.sanitize(marked.parse($('content').value||''))+'</div>';$('previewModal').classList.remove('hidden')};
$('closePreview').onclick=()=>$('previewModal').classList.add('hidden');$('previewModal').addEventListener('click',e=>{if(e.target===$('previewModal'))$('previewModal').classList.add('hidden')});