create extension if not exists pg_trgm;
create table if not exists public.categories(id bigint generated by default as identity primary key,name text not null unique,slug text not null unique,description text default '',created_at timestamptz not null default now());
create table if not exists public.articles(id bigint generated by default as identity primary key,title text not null,slug text not null unique,excerpt text not null default '',content text not null,category text not null,tags text[] not null default '{}',status text not null default 'draft' check(status in ('draft','published')),published_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists articles_status_published_idx on public.articles(status,published_at desc);
create index if not exists articles_category_idx on public.articles(category);
create index if not exists articles_title_trgm_idx on public.articles using gin(title gin_trgm_ops);
create index if not exists articles_excerpt_trgm_idx on public.articles using gin(excerpt gin_trgm_ops);
alter table public.categories enable row level security;
alter table public.articles enable row level security;
drop policy if exists "public read categories" on public.categories;
create policy "public read categories" on public.categories for select to anon,authenticated using (true);
drop policy if exists "public read published articles" on public.articles;
create policy "public read published articles" on public.articles for select to anon,authenticated using (status='published');
insert into public.categories(name,slug) values ('Robotics','robotics'),('Code','code'),('PC & Tech','pc-tech'),('Projects','projects') on conflict (slug) do nothing;
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists articles_updated_at on public.articles;
create trigger articles_updated_at before update on public.articles for each row execute function public.set_updated_at();
-- After creating the admin Auth user, run:
-- update auth.users set raw_app_meta_data=coalesce(raw_app_meta_data,'{}'::jsonb)||'{"role":"admin"}'::jsonb where email='YOUR_ADMIN_EMAIL';